# Azure Pipelines configuration that builds and packages the extension.
# To learn more about Azure Pipelines: https://aka.ms/learn-azure-pipelines

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: azure-pipelines-steps.yml

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: azure-pipelines-steps.yml
  
- job: always
  steps:
  - script: echo "The build has finished"
    condition: always()

- job: success
  steps:
  - script: echo "Hurrah!!! The build succeeded"
    condition: succeeded()

- job: failed
  steps:
  - script: echo "The build failed"
    condition: failed()
  
